language: php

env:
  - USE_LATEST_DEPS=false
  - USE_LATEST_DEPS=true

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install --prefer-dist

before_script:
  - if $USE_LATEST_DEPS; then composer update; fi;

script:
  - ${COMPOSER_BIN_DIR}/phpcs --standard=PSR2 src && ${COMPOSER_BIN_DIR}/phpcs --standard=PSR2 config && ${COMPOSER_BIN_DIR}/phpcs --standard=PSR2 tests && ${COMPOSER_BIN_DIR}/phpunit tests -v -c tests/phpunit.xml && ${COMPOSER_BIN_DIR}/phpmd config,src,tests text cleancode,codesize,controversial,design,naming,unusedcode

after_success:
  - ${COMPOSER_BIN_DIR}/test-reporter